# Generated by Django 5.2.4 on 2025-09-25 16:01

import app01.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_type", models.CharField(max_length=20)),
                ("A_answer", models.TextField(blank=True, null=True)),
                ("B_answer", models.TextField(blank=True, null=True)),
                ("C_answer", models.TextField(blank=True, null=True)),
                ("D_answer", models.TextField(blank=True, null=True)),
                ("content", models.TextField()),
                ("answer", models.TextField()),
                ("score", models.IntegerField()),
                ("batch", models.IntegerField(blank=True, null=True)),
                ("analysis", models.TextField(blank=True, null=True)),
                (
                    "knowledge_points",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "primary_knowledge",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=10)),
                ("fingerprint", models.BinaryField(blank=True, null=True)),
                ("department", models.CharField(max_length=50)),
                ("classroom", models.CharField(max_length=50)),
                ("nickname", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("student_no", models.CharField(blank=True, default="", max_length=50)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app01.models.user_avatar_upload_to,
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="ExamRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("submit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
            options={
                "db_table": "exam_records",
            },
        ),
        migrations.CreateModel(
            name="AnswerRecord",
            fields=[
                ("answer_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_answer", models.TextField()),
                ("is_correct", models.BooleanField()),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.examrecord",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.question"
                    ),
                ),
            ],
            options={
                "db_table": "answer_records",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.exam"
                    ),
                ),
            ],
            options={
                "db_table": "exam_questions",
                "unique_together": {("exam", "batch")},
            },
        ),
        migrations.CreateModel(
            name="OperationDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("total", models.IntegerField(blank=True, null=True)),
                ("msg", models.TextField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_details",
                        to="app01.examrecord",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.question"
                    ),
                ),
            ],
            options={
                "db_table": "operation_details",
                "indexes": [
                    models.Index(
                        fields=["record"], name="operation_d_record__5b1d27_idx"
                    ),
                    models.Index(
                        fields=["question"], name="operation_d_questio_97d50b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionReview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "suggested_answer",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "suggested_kp",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "suggested_primary",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("suggested_analysis", models.TextField(blank=True, default="")),
                ("answer_wrong", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
            options={
                "db_table": "question_reviews",
                "indexes": [
                    models.Index(
                        fields=["question"], name="question_re_questio_376197_idx"
                    ),
                    models.Index(
                        fields=["user"], name="question_re_user_id_f227b4_idx"
                    ),
                ],
                "unique_together": {("user", "question")},
            },
        ),
        migrations.CreateModel(
            name="QuestionComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
            options={
                "db_table": "question_comments",
                "indexes": [
                    models.Index(
                        fields=["question"], name="question_co_questio_10ad54_idx"
                    ),
                    models.Index(
                        fields=["user"], name="question_co_user_id_a31855_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PracticeAnswer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_attempts", models.IntegerField(default=0)),
                ("correct_attempts", models.IntegerField(default=0)),
                ("last_is_correct", models.BooleanField(default=False)),
                ("last_answer_time", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.user",
                    ),
                ),
            ],
            options={
                "db_table": "practice_answers",
                "indexes": [
                    models.Index(
                        fields=["user"], name="practice_an_user_id_21b51b_idx"
                    ),
                    models.Index(
                        fields=["question"], name="practice_an_questio_cc0951_idx"
                    ),
                ],
                "unique_together": {("user", "question")},
            },
        ),
        migrations.CreateModel(
            name="FaceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app01.models.user_face_upload_to,
                    ),
                ),
                ("vector", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_profile",
                        to="app01.user",
                    ),
                ),
            ],
            options={
                "db_table": "face_profiles",
                "indexes": [
                    models.Index(fields=["user"], name="face_profil_user_id_49b59d_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ExamSignIn",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("success", models.BooleanField(default=False)),
                ("method", models.CharField(blank=True, default="", max_length=20)),
                ("score", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
            options={
                "db_table": "exam_signins",
                "indexes": [
                    models.Index(
                        fields=["exam"], name="exam_signin_exam_id_c23103_idx"
                    ),
                    models.Index(
                        fields=["user"], name="exam_signin_user_id_af7a3d_idx"
                    ),
                    models.Index(
                        fields=["exam", "user", "created_at"],
                        name="exam_signin_exam_id_ff638a_idx",
                    ),
                ],
            },
        ),
    ]
