# Generated by Django 5.2.4 on 2025-09-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionCommentLike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="app01.questioncomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
            options={
                "db_table": "question_comment_likes",
                "indexes": [
                    models.Index(
                        fields=["comment"], name="question_co_comment_f72c7e_idx"
                    ),
                    models.Index(
                        fields=["user"], name="question_co_user_id_841ce7_idx"
                    ),
                ],
                "unique_together": {("comment", "user")},
            },
        ),
    ]
