# Generated by Django 5.2.4 on 2025-09-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_questioncommentlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyllabusItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("province", models.CharField(max_length=50)),
                ("major", models.CharField(max_length=50)),
                ("kp", models.CharField(max_length=255)),
                ("primary", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "syllabus_items",
                "indexes": [
                    models.Index(
                        fields=["province", "major"],
                        name="syllabus_it_provinc_65992b_idx",
                    ),
                    models.Index(fields=["kp"], name="syllabus_it_kp_f362e7_idx"),
                ],
            },
        ),
    ]
