# Generated by Django 5.2.4 on 2025-09-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_syllabusitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="syllabusitem",
            unique_together={("province", "major", "kp", "primary")},
        ),
    ]
