# Generated by Django 5.2.4 on 2025-09-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_alter_syllabusitem_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "global_settings",
            },
        ),
        migrations.AddField(
            model_name="faceprofile",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="人脸有效期（审核通过起1个月，到期需重新审核）",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vip_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="VIP 到期时间（到期自动降级为学生）", null=True
            ),
        ),
    ]
