# Generated by Django 5.2.4 on 2025-09-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_globalsetting_faceprofile_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
