"""
Django settings for Django project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 最小改动：允许通过环境变量覆盖，未设置时回退原开发密钥（请在生产设置 DJANGO_SECRET_KEY）
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-zg1qn$a1+ki40qm8jp0jlr$y-gxx4!9ux)ofviam=r_w+ic5tk')

# 最小改动：DEBUG 支持环境变量开关（生产设置 DJANGO_DEBUG=0）
DEBUG = os.getenv('DJANGO_DEBUG', '1').lower() in ('1', 'true', 'yes')

# 最小改动：生产环境需显式 ALLOWED_HOSTS（逗号分隔），开发保留 '*'
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    _hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '')
    ALLOWED_HOSTS = [h.strip() for h in _hosts.split(',') if h.strip()] or ['localhost']

# 允许跨域（开发环境）：放开来源并允许携带凭证
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# 信任的前端来源（POST/登录等需要）
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://10.253.148.223:5173',
    'http://192.168.137.1:5173',
    'http://192.168.56.1:5173',
    'http://192.168.182.1:5173',
    'http://192.168.206.1:5173',
]

# 跨站携带会话所需（开发）：使用 Lax，适配同站点不同端口（HTTP）
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # 生产自动开启 Secure
CSRF_COOKIE_SECURE = not DEBUG
# 新增：HttpOnly 防止前端脚本读取
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# 新增：会话配置（浏览器关闭即过期；可选最大存活时长）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', str(14 * 24 * 60 * 60)))  # 14 天（仅在浏览器不关闭时作为上限）
# 单端登录开关（默认开启；生产可通过环境变量关闭）
SINGLE_SESSION_ENFORCE = os.getenv('SINGLE_SESSION_ENFORCE', '1').lower() in ('1', 'true', 'yes')

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 删除重复的 CommonMiddleware（此前已出现一次）
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # 如需开启 CSRF，设置 DJANGO_ENABLE_CSRF=1 并取消注释
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app01.middleware.SessionAuthRequiredMiddleware',  # 自定义登录校验
    'app01.middleware.SecurityHeadersMiddleware',      # 新增：安全响应头与反爬虫基础
]

# 可选：运行时按需启用 CSRF 中间件（最小侵入，不破坏现有前端）
if os.getenv('DJANGO_ENABLE_CSRF', '0').lower() in ('1', 'true', 'yes'):
    try:
        i = MIDDLEWARE.index('django.middleware.security.SecurityMiddleware')
    except ValueError:
        i = 0
    MIDDLEWARE.insert(i + 1, 'django.middleware.csrf.CsrfViewMiddleware')

ROOT_URLCONF = 'Django.urls'

# CORS 配置，允许指定来源访问（开发环境）
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:5173',
#     'http://127.0.0.1:3000',
#     'http://127.0.0.1:5173',
# ]
# 允许携带凭证（如 cookies、authorization headers）
# CORS_ALLOW_CREDENTIALS = True

# 允许的请求头
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "accept",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]

# REST framework 配置，推荐使用 JSON 渲染器
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'app01.api.utils.CsrfExemptSessionAuthentication',  # 免 CSRF 的会话认证
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_RATE_ANON', '200/min'),
        'user': os.getenv('DRF_THROTTLE_RATE_USER', '600/min'),
        # 可选：针对敏感接口的命名限流（如启用 throttle_scope）
        'login': os.getenv('DRF_THROTTLE_RATE_LOGIN', '20/min'),
        'register': os.getenv('DRF_THROTTLE_RATE_REGISTER', '10/min'),
        'face': os.getenv('DRF_THROTTLE_RATE_FACE', '30/min'),
        'import': os.getenv('DRF_THROTTLE_RATE_IMPORT', '10/min'),
    },
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
    'EXCEPTION_HANDLER': 'app01.api.utils.custom_exception_handler',
}

# 静态文件配置（如需提供静态资源给前端）
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'app01' / 'static',
    # 生产最省事：让 Django 直接托管 Vite 打包产物（my-front-end/dist）
    BASE_DIR.parent / 'my-front-end' / 'dist',
]
# collectstatic 收集到此目录（生产建议开启）
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒体文件（用户上传，如头像）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 模板目录可留空或移除，前后端分离时后端不渲染页面
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'exam_system',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# 测试环境使用 sqlite，避免依赖 MySQL 服务
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'testdb.sqlite3'
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================== 百度AI人脸识别配置 ==================
# 最小改动：仍使用硬编码，生产可改为：os.getenv('BAIDU_FACE_APP_ID') 等（保持当前行为不破坏）
BAIDU_FACE = {
    'APP_ID': os.getenv('BAIDU_FACE_APP_ID', '119819856'),
    'API_KEY': os.getenv('BAIDU_FACE_API_KEY', 'IL2AOntFfPt2Bi169zbwOmv2'),
    'SECRET_KEY': os.getenv('BAIDU_FACE_SECRET_KEY', 'EO5LenhwhV6zEz8lY35XkK1QKAfbHvgu'),
    'GROUP_ID': os.getenv('BAIDU_FACE_GROUP_ID', 'exam_users'),
    'THRESHOLD': float(os.getenv('BAIDU_FACE_THRESHOLD', '60.0')),
}
FACE_SIGNIN_TTL_MINUTES = int(os.getenv('FACE_SIGNIN_TTL_MINUTES', '120'))
LOCAL_FACE = { 'THRESHOLD': float(os.getenv('LOCAL_FACE_THRESHOLD', '85.0')) }

# 新增：公开注册开关（前端注册接口使用）
ALLOW_PUBLIC_REGISTRATION = os.getenv('ALLOW_PUBLIC_REGISTRATION', '1').lower() in ('1','true','yes')

# 新增：上传/请求大小限制（防止大包耗尽内存）
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', str(10*1024*1024)))   # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', str(5*1024*1024)))     # 5MB
AVATAR_MAX_BYTES = int(os.getenv('AVATAR_MAX_BYTES', str(2*1024*1024)))       # 2MB 头像
FACE_IMAGE_MAX_BYTES = int(os.getenv('FACE_IMAGE_MAX_BYTES', str(3*1024*1024))) # 3MB 人脸
EXCEL_MAX_BYTES = int(os.getenv('EXCEL_MAX_BYTES', str(8*1024*1024)))         # 8MB 题目导入

# 可选：代理/容器下识别 HTTPS
if os.getenv('USE_X_FORWARDED_HOST','0').lower() in ('1','true','yes'):
    USE_X_FORWARDED_HOST = True
if os.getenv('SECURE_PROXY_SSL_HEADER',''):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO','https')

# 缓存：默认使用内存缓存；生产可通过 REDIS_URL 启用 Redis 以支持多进程/多机共享
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'exam_system_locmem',
    }
}
_redis_url = os.getenv('REDIS_URL')
if _redis_url:
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': _redis_url,
    }

# 提示：生产部署至少需要设置：DJANGO_SECRET_KEY, DJANGO_DEBUG=0, DJANGO_ALLOWED_HOSTS, DB_NAME, DB_USER, DB_PASSWORD, ALLOW_PUBLIC_REGISTRATION=0（如需关闭注册）
# 其余改动保持最小，不影响当前开发运行。
